### ISSUE TITLE
Visualizacion de perfil de otros usuarios

### ISSUE THREAD

**Issue by hgmart** [el-unico-match/users#11]
Como Usuario quiero poder visualizar los datos de los otros usuarios para conocer su información de contacto
Criterios de aceptación

CA 1: Visualización de perfil de otros usuarios
Cuando se visualice el perfil de un usuario que no es propietario de la cuenta
Entonces estos se visualizarán datos públicos del usuario

**Comment by FontiLucas** [comment]
Terminado el Front
