### ISSUE TITLE
Registro de usuarios

### ISSUE THREAD

**Issue by hgmart** [el-unico-match/users#3]
Como usuario no registrado quiero registrarme en la plataforma para acceder a las funcionalidades del sistema.
En el resto de los CA se utilizará la nomenclatura Usuario como un usuario registrado

Criterios de aceptación

CA 1: Registro exitoso
Cuando el registro del usuario es correcto.
Entonces el sistema creará un nuevo usuario con su perfil. Luego permitirá el ingreso al sistema.
CA 2: Obtención de ubicación
Cuando el registro del usuario es correcto.
Entonces el sistema deberá solicitarle al usuario una ubicación predeterminada
CA 3: Obtención de perfil
Cuando el registro del usuario es correcto.
Entonces el sistema deberá solicitarle al usuario cuales son sus intereses.
CA 4: Obtención de fotos
Cuando el registro del usuario es correcto.
Entonces el sistema debera solicitar al usuario al menos 3 fotos para utilizar en el perfil
El usuario debera indicar su foto principal de perfil
CA 5: Biografia
Cuando el registro del usuario es correcto.
Entonces el sistema debera solicitar al usuario una descripcion de si mismo para mostrar
CA 4: Falta uno o más campos obligatorios
Cuando el registro del usuario es incorrecto debido a un ingreso erróneo o faltante de campos.
Entonces el sistema indicará los campos faltantes y/o erróneos y no permitirá el ingreso al sistema.
CA 5: Registro fallido
Cuando el registro del usuario falla debido a un error del servicio.
Entonces el sistema indicará un mensaje de error acorde al usuario.

**Comment by FontiLucas** [comment]
Listo de mi lado.

**Comment by hgmart** [comment]
Falta el 
CA2: registrar posiciones en el backend
CA4: registrar foto principipal en el backend
