### ISSUE TITLE
Notificación de PIN en proceso de registro (opcional) ?

### ISSUE THREAD

**Issue by hgmart** [el-unico-match/users#4]
Como usuario quiero poder recibir una notificación con un código de seguridad, para confirmar mi registración. Pudiendo optar entre alguno de estos CA
Criterios de aceptación

CA 1: Notificación whatsapp:
Cuando un usuario se registra de manera exitosa en la plataforma
Entonces deberá recibir un mensaje de whatsapp con un PIN generado por la plataforma, para confirmar la registración
CA 2: Notificación Email:
Cuando un usuario se registra de manera exitosa en la plataforma
Entonces deberá recibir un correo electronico con un PIN generado por la plataforma, para confirmar la registración

**Comment by diegofiuba** [comment]
Optamos por el CA2
