### ISSUE TITLE
Edición de perfil

### ISSUE THREAD

**Issue by hgmart** [el-unico-match/users#9]
Como Usuario quiero poder editar los datos de mi perfil de usuario para mantener actualizada mi información personal.
Criterios de aceptación

CA 1: Edición de datos de perfil exitosa
Cuando se modifican los datos de la cuenta del Usuario de manera exitosa
Entonces estos nuevos datos serán los que se utilicen como datos de perfil de usuario
En caso contrario se deberá mostrar un mensaje de error acorde al usuario.
CA 2: Ordenamiento de fotos
Cuando el usuario esta en la pantalla de edicion de perfil,
Entonces debera poder sumar, quitar y ordenar las fotos para elegir en que orden y cuales se muestran

**Comment by FontiLucas** [comment]
Front terminado

**Comment by hgmart** [comment]
Falta agregar en Pictures la opción para ocultar imágenes, la principal y el avatar.
